FROM node:18.14.2-alpine3.17  
# Set the working directory to /app
WORKDIR /app
# Install dependencies
COPY ./package.json ./
RUN npm install
# Install nodemon globally for live reloading
RUN npm install -g nodemon
COPY . .
CMD ["npm","start"]